// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/extension-daemon/disconnect.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package extension_daemon

import "encoding/json"
import "fmt"
import "reflect"

// Extension -> Daemon. Sent on `session_shutdown`. See SPEC.md §§ 6.6, 10.1.
type DisconnectJson struct {
	// Reason corresponds to the JSON schema field "reason".
	Reason DisconnectJsonReason `json:"reason"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`
}

type DisconnectJsonReason string

const DisconnectJsonReasonClientRequest DisconnectJsonReason = "client_request"
const DisconnectJsonReasonError DisconnectJsonReason = "error"
const DisconnectJsonReasonSessionShutdown DisconnectJsonReason = "session_shutdown"

var enumValues_DisconnectJsonReason = []interface{}{
	"session_shutdown",
	"client_request",
	"error",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DisconnectJsonReason) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DisconnectJsonReason {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_DisconnectJsonReason, v)
	}
	*j = DisconnectJsonReason(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DisconnectJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["reason"]; raw != nil && !ok {
		return fmt.Errorf("field reason in DisconnectJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in DisconnectJson: required")
	}
	type Plain DisconnectJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = DisconnectJson(plain)
	return nil
}
