// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/extension-daemon/heartbeat.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package extension_daemon

import "encoding/json"
import "fmt"

// Extension -> Daemon. 10-second cadence liveness ping. See SPEC.md §§ 6.6, 10.1.
type HeartbeatJson struct {
	// Unix epoch milliseconds.
	Ts int `json:"ts"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *HeartbeatJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["ts"]; raw != nil && !ok {
		return fmt.Errorf("field ts in HeartbeatJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in HeartbeatJson: required")
	}
	type Plain HeartbeatJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.Ts {
		return fmt.Errorf("field %s: must be >= %v", "ts", 0)
	}
	*j = HeartbeatJson(plain)
	return nil
}
