// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/push/push_payload.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package push

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"

// Plaintext (pre-crypto_box) push payload sent from coordinator to phone via ntfy.
// See SPEC.md § 10.4.
type PushPayloadJson struct {
	// DeepLink corresponds to the JSON schema field "deep_link".
	DeepLink string `json:"deep_link"`

	// Kind corresponds to the JSON schema field "kind".
	Kind PushPayloadJsonKind `json:"kind"`

	// MachineDisplayName corresponds to the JSON schema field "machine_display_name".
	MachineDisplayName string `json:"machine_display_name"`

	// MachineId corresponds to the JSON schema field "machine_id".
	MachineId string `json:"machine_id"`

	// ProjectDisplayName corresponds to the JSON schema field "project_display_name".
	ProjectDisplayName PushPayloadJsonProjectDisplayName `json:"project_display_name,omitempty,omitzero"`

	// ProjectName corresponds to the JSON schema field "project_name".
	ProjectName string `json:"project_name"`

	// Reason corresponds to the JSON schema field "reason".
	Reason PushPayloadJsonReason `json:"reason"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id"`

	// Summary corresponds to the JSON schema field "summary".
	Summary string `json:"summary"`

	// Ts corresponds to the JSON schema field "ts".
	Ts int `json:"ts"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

type PushPayloadJsonKind string

const PushPayloadJsonKindNeedsAttention PushPayloadJsonKind = "needs_attention"

var enumValues_PushPayloadJsonKind = []interface{}{
	"needs_attention",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PushPayloadJsonKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_PushPayloadJsonKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_PushPayloadJsonKind, v)
	}
	*j = PushPayloadJsonKind(v)
	return nil
}

type PushPayloadJsonProjectDisplayName *string

type PushPayloadJsonReason string

const PushPayloadJsonReasonAgentIdle PushPayloadJsonReason = "agent_idle"
const PushPayloadJsonReasonCompactionComplete PushPayloadJsonReason = "compaction_complete"
const PushPayloadJsonReasonExtensionDialog PushPayloadJsonReason = "extension_dialog"
const PushPayloadJsonReasonExtensionError PushPayloadJsonReason = "extension_error"
const PushPayloadJsonReasonMachineSuspended PushPayloadJsonReason = "machine_suspended"
const PushPayloadJsonReasonQueueUpdate PushPayloadJsonReason = "queue_update"
const PushPayloadJsonReasonSessionEnded PushPayloadJsonReason = "session_ended"
const PushPayloadJsonReasonToolFailure PushPayloadJsonReason = "tool_failure"
const PushPayloadJsonReasonUnresponsive PushPayloadJsonReason = "unresponsive"

var enumValues_PushPayloadJsonReason = []interface{}{
	"agent_idle",
	"extension_dialog",
	"tool_failure",
	"queue_update",
	"extension_error",
	"compaction_complete",
	"machine_suspended",
	"session_ended",
	"unresponsive",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PushPayloadJsonReason) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_PushPayloadJsonReason {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_PushPayloadJsonReason, v)
	}
	*j = PushPayloadJsonReason(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PushPayloadJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["deep_link"]; raw != nil && !ok {
		return fmt.Errorf("field deep_link in PushPayloadJson: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in PushPayloadJson: required")
	}
	if _, ok := raw["machine_display_name"]; raw != nil && !ok {
		return fmt.Errorf("field machine_display_name in PushPayloadJson: required")
	}
	if _, ok := raw["machine_id"]; raw != nil && !ok {
		return fmt.Errorf("field machine_id in PushPayloadJson: required")
	}
	if _, ok := raw["project_name"]; raw != nil && !ok {
		return fmt.Errorf("field project_name in PushPayloadJson: required")
	}
	if _, ok := raw["reason"]; raw != nil && !ok {
		return fmt.Errorf("field reason in PushPayloadJson: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in PushPayloadJson: required")
	}
	if _, ok := raw["summary"]; raw != nil && !ok {
		return fmt.Errorf("field summary in PushPayloadJson: required")
	}
	if _, ok := raw["ts"]; raw != nil && !ok {
		return fmt.Errorf("field ts in PushPayloadJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in PushPayloadJson: required")
	}
	type Plain PushPayloadJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^pi-remote://`, string(plain.DeepLink)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "DeepLink", `^pi-remote://`)
	}
	if 0 > plain.Ts {
		return fmt.Errorf("field %s: must be >= %v", "ts", 0)
	}
	*j = PushPayloadJson(plain)
	return nil
}
