// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/daemon-coordinator/pty_resize.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package daemon_coordinator

import "encoding/json"
import "fmt"

// Coordinator -> Daemon (originating from a client). Structured pane resize. See
// SPEC.md § 14.5.
type PtyResizeJson struct {
	// Cols corresponds to the JSON schema field "cols".
	Cols int `json:"cols"`

	// Rows corresponds to the JSON schema field "rows".
	Rows int `json:"rows"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PtyResizeJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["cols"]; raw != nil && !ok {
		return fmt.Errorf("field cols in PtyResizeJson: required")
	}
	if _, ok := raw["rows"]; raw != nil && !ok {
		return fmt.Errorf("field rows in PtyResizeJson: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in PtyResizeJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in PtyResizeJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in PtyResizeJson: required")
	}
	type Plain PtyResizeJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain.Cols {
		return fmt.Errorf("field %s: must be >= %v", "cols", 1)
	}
	if 1 > plain.Rows {
		return fmt.Errorf("field %s: must be >= %v", "rows", 1)
	}
	*j = PtyResizeJson(plain)
	return nil
}
