// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/daemon-coordinator/session_state_change.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package daemon_coordinator

import "encoding/json"
import "fmt"
import "reflect"

// Daemon -> Coordinator (also forwarded to App). Session state transition. See
// SPEC.md §§ 10.2, 10.3, 12.
type SessionStateChangeJson struct {
	// From corresponds to the JSON schema field "from".
	From State `json:"from"`

	// Seq corresponds to the JSON schema field "seq".
	Seq int `json:"seq"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id"`

	// To corresponds to the JSON schema field "to".
	To State `json:"to"`

	// Ts corresponds to the JSON schema field "ts".
	Ts int `json:"ts"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SessionStateChangeJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["from"]; raw != nil && !ok {
		return fmt.Errorf("field from in SessionStateChangeJson: required")
	}
	if _, ok := raw["seq"]; raw != nil && !ok {
		return fmt.Errorf("field seq in SessionStateChangeJson: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in SessionStateChangeJson: required")
	}
	if _, ok := raw["to"]; raw != nil && !ok {
		return fmt.Errorf("field to in SessionStateChangeJson: required")
	}
	if _, ok := raw["ts"]; raw != nil && !ok {
		return fmt.Errorf("field ts in SessionStateChangeJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SessionStateChangeJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in SessionStateChangeJson: required")
	}
	type Plain SessionStateChangeJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain.Seq {
		return fmt.Errorf("field %s: must be >= %v", "seq", 1)
	}
	if 0 > plain.Ts {
		return fmt.Errorf("field %s: must be >= %v", "ts", 0)
	}
	*j = SessionStateChangeJson(plain)
	return nil
}

type State string

const StateEnded State = "ended"
const StateIdle State = "idle"
const StatePaused State = "paused"
const StateRunning State = "running"
const StateUnresponsive State = "unresponsive"

var enumValues_State = []interface{}{
	"running",
	"idle",
	"paused",
	"unresponsive",
	"ended",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *State) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_State {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_State, v)
	}
	*j = State(v)
	return nil
}
