// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/daemon-coordinator/session_event.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package daemon_coordinator

import "encoding/json"
import "fmt"
import "reflect"

// Daemon -> Coordinator (also Coordinator -> App). Structured session event with
// monotonic per-session seq. See SPEC.md §§ 10.2, 10.3.
type SessionEventJson struct {
	// Data corresponds to the JSON schema field "data".
	Data SessionEventJsonData `json:"data"`

	// Kind corresponds to the JSON schema field "kind".
	Kind SessionEventJsonKind `json:"kind"`

	// Seq corresponds to the JSON schema field "seq".
	Seq int `json:"seq"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id"`

	// Ts corresponds to the JSON schema field "ts".
	Ts int `json:"ts"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

type SessionEventJsonData map[string]interface{}

type SessionEventJsonKind string

const SessionEventJsonKindAgentEnd SessionEventJsonKind = "agent_end"
const SessionEventJsonKindAgentStart SessionEventJsonKind = "agent_start"
const SessionEventJsonKindAttentionDialog SessionEventJsonKind = "attention_dialog"
const SessionEventJsonKindCompactionEnd SessionEventJsonKind = "compaction_end"
const SessionEventJsonKindCompactionStart SessionEventJsonKind = "compaction_start"
const SessionEventJsonKindExtensionError SessionEventJsonKind = "extension_error"
const SessionEventJsonKindModelSelect SessionEventJsonKind = "model_select"
const SessionEventJsonKindQueueUpdate SessionEventJsonKind = "queue_update"
const SessionEventJsonKindToolFailure SessionEventJsonKind = "tool_failure"

var enumValues_SessionEventJsonKind = []interface{}{
	"agent_start",
	"agent_end",
	"attention_dialog",
	"tool_failure",
	"queue_update",
	"model_select",
	"compaction_start",
	"compaction_end",
	"extension_error",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SessionEventJsonKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SessionEventJsonKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SessionEventJsonKind, v)
	}
	*j = SessionEventJsonKind(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SessionEventJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in SessionEventJson: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in SessionEventJson: required")
	}
	if _, ok := raw["seq"]; raw != nil && !ok {
		return fmt.Errorf("field seq in SessionEventJson: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in SessionEventJson: required")
	}
	if _, ok := raw["ts"]; raw != nil && !ok {
		return fmt.Errorf("field ts in SessionEventJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SessionEventJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in SessionEventJson: required")
	}
	type Plain SessionEventJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain.Seq {
		return fmt.Errorf("field %s: must be >= %v", "seq", 1)
	}
	if 0 > plain.Ts {
		return fmt.Errorf("field %s: must be >= %v", "ts", 0)
	}
	*j = SessionEventJson(plain)
	return nil
}
