// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/daemon-coordinator/session_pty.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package daemon_coordinator

import "encoding/json"
import "fmt"
import "reflect"

// Daemon -> Coordinator (also Coordinator -> App). Pty bytes from a session. See
// SPEC.md §§ 10.2, 10.3, 24 (compression reserved).
type SessionPtyJson struct {
	// Base64-encoded raw pty bytes.
	Bytes string `json:"bytes"`

	// Reserved for v2 (zstd). v1 omits or sets to null.
	Compression *SessionPtyJsonCompression `json:"compression,omitempty,omitzero"`

	// Seq corresponds to the JSON schema field "seq".
	Seq int `json:"seq"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id"`

	// Ts corresponds to the JSON schema field "ts".
	Ts int `json:"ts"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

type SessionPtyJsonCompression struct {
	Value interface{}
}

// MarshalJSON implements json.Marshaler.
func (j *SessionPtyJsonCompression) MarshalJSON() ([]byte, error) {
	return json.Marshal(j.Value)
}

var enumValues_SessionPtyJsonCompression = []interface{}{
	nil,
	"none",
	"zstd",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SessionPtyJsonCompression) UnmarshalJSON(value []byte) error {
	var v struct {
		Value interface{}
	}
	if err := json.Unmarshal(value, &v.Value); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SessionPtyJsonCompression {
		if reflect.DeepEqual(v.Value, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SessionPtyJsonCompression, v.Value)
	}
	*j = SessionPtyJsonCompression(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SessionPtyJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bytes"]; raw != nil && !ok {
		return fmt.Errorf("field bytes in SessionPtyJson: required")
	}
	if _, ok := raw["seq"]; raw != nil && !ok {
		return fmt.Errorf("field seq in SessionPtyJson: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in SessionPtyJson: required")
	}
	if _, ok := raw["ts"]; raw != nil && !ok {
		return fmt.Errorf("field ts in SessionPtyJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SessionPtyJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in SessionPtyJson: required")
	}
	type Plain SessionPtyJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain.Seq {
		return fmt.Errorf("field %s: must be >= %v", "seq", 1)
	}
	if 0 > plain.Ts {
		return fmt.Errorf("field %s: must be >= %v", "ts", 0)
	}
	*j = SessionPtyJson(plain)
	return nil
}
