// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/daemon-coordinator/session_resume.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package daemon_coordinator

import "encoding/json"
import "fmt"

// Daemon -> Coordinator. Sent on reconnect for each still-live Pi session. Carries
// the daemon's last emitted seq so the broker can compute backfill availability.
// See SPEC.md §§ 7.8, 10.2.
type SessionResumeJson struct {
	// LastSeqEmitted corresponds to the JSON schema field "last_seq_emitted".
	LastSeqEmitted int `json:"last_seq_emitted"`

	// Metadata corresponds to the JSON schema field "metadata".
	Metadata SessionResumeJsonMetadata `json:"metadata"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

type SessionResumeJsonMetadata map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SessionResumeJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["last_seq_emitted"]; raw != nil && !ok {
		return fmt.Errorf("field last_seq_emitted in SessionResumeJson: required")
	}
	if _, ok := raw["metadata"]; raw != nil && !ok {
		return fmt.Errorf("field metadata in SessionResumeJson: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in SessionResumeJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SessionResumeJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in SessionResumeJson: required")
	}
	type Plain SessionResumeJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.LastSeqEmitted {
		return fmt.Errorf("field %s: must be >= %v", "last_seq_emitted", 0)
	}
	*j = SessionResumeJson(plain)
	return nil
}
