// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/daemon-coordinator/session_started.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package daemon_coordinator

import "encoding/json"
import "fmt"

// Daemon -> Coordinator. Emitted when a Pi session registers with the daemon. The
// same shape is forwarded by the coordinator to clients. See SPEC.md §§ 10.2,
// 10.3.
type SessionStartedJson struct {
	// MachineId corresponds to the JSON schema field "machine_id".
	MachineId string `json:"machine_id"`

	// Metadata corresponds to the JSON schema field "metadata".
	Metadata SessionStartedJsonMetadata `json:"metadata"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

type SessionStartedJsonMetadata struct {
	// Cwd corresponds to the JSON schema field "cwd".
	Cwd string `json:"cwd"`

	// Hostname corresponds to the JSON schema field "hostname".
	Hostname string `json:"hostname"`

	// Model corresponds to the JSON schema field "model".
	Model string `json:"model"`

	// ProjectDisplayName corresponds to the JSON schema field "project_display_name".
	ProjectDisplayName SessionStartedJsonMetadataProjectDisplayName `json:"project_display_name,omitempty,omitzero"`

	// ProjectName corresponds to the JSON schema field "project_name".
	ProjectName string `json:"project_name"`

	// SpawnToken corresponds to the JSON schema field "spawn_token".
	SpawnToken SessionStartedJsonMetadataSpawnToken `json:"spawn_token,omitempty,omitzero"`

	// StartedAt corresponds to the JSON schema field "started_at".
	StartedAt int `json:"started_at"`
}

type SessionStartedJsonMetadataProjectDisplayName *string

type SessionStartedJsonMetadataSpawnToken *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *SessionStartedJsonMetadata) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["cwd"]; raw != nil && !ok {
		return fmt.Errorf("field cwd in SessionStartedJsonMetadata: required")
	}
	if _, ok := raw["hostname"]; raw != nil && !ok {
		return fmt.Errorf("field hostname in SessionStartedJsonMetadata: required")
	}
	if _, ok := raw["model"]; raw != nil && !ok {
		return fmt.Errorf("field model in SessionStartedJsonMetadata: required")
	}
	if _, ok := raw["project_name"]; raw != nil && !ok {
		return fmt.Errorf("field project_name in SessionStartedJsonMetadata: required")
	}
	if _, ok := raw["started_at"]; raw != nil && !ok {
		return fmt.Errorf("field started_at in SessionStartedJsonMetadata: required")
	}
	type Plain SessionStartedJsonMetadata
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.StartedAt {
		return fmt.Errorf("field %s: must be >= %v", "started_at", 0)
	}
	*j = SessionStartedJsonMetadata(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SessionStartedJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["machine_id"]; raw != nil && !ok {
		return fmt.Errorf("field machine_id in SessionStartedJson: required")
	}
	if _, ok := raw["metadata"]; raw != nil && !ok {
		return fmt.Errorf("field metadata in SessionStartedJson: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in SessionStartedJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SessionStartedJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in SessionStartedJson: required")
	}
	type Plain SessionStartedJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SessionStartedJson(plain)
	return nil
}
