// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/coordinator-app/client_focus.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package coordinator_app

import "encoding/json"
import "fmt"

// App -> Coordinator. Reports whether the session is currently in the foreground
// for this client (used to suppress push). See SPEC.md §§ 9.7, 10.3.
type ClientFocusJson struct {
	// Focused corresponds to the JSON schema field "focused".
	Focused bool `json:"focused"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClientFocusJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["focused"]; raw != nil && !ok {
		return fmt.Errorf("field focused in ClientFocusJson: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in ClientFocusJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in ClientFocusJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in ClientFocusJson: required")
	}
	type Plain ClientFocusJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ClientFocusJson(plain)
	return nil
}
