// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/coordinator-app/client_hello.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package coordinator_app

import "encoding/json"
import "fmt"

// App -> Coordinator. First message after WebSocket open. See SPEC.md § 10.3.
type ClientHelloJson struct {
	// AppVersion corresponds to the JSON schema field "app_version".
	AppVersion string `json:"app_version"`

	// ClientId corresponds to the JSON schema field "client_id".
	ClientId string `json:"client_id"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClientHelloJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["app_version"]; raw != nil && !ok {
		return fmt.Errorf("field app_version in ClientHelloJson: required")
	}
	if _, ok := raw["client_id"]; raw != nil && !ok {
		return fmt.Errorf("field client_id in ClientHelloJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in ClientHelloJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in ClientHelloJson: required")
	}
	type Plain ClientHelloJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ClientHelloJson(plain)
	return nil
}
