// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/coordinator-app/machine_list.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package coordinator_app

import "encoding/json"
import "fmt"
import "reflect"

// Coordinator -> App. Initial list and subsequent full snapshots of machines and
// their sessions. See SPEC.md § 10.3.
type MachineListJson struct {
	// Machines corresponds to the JSON schema field "machines".
	Machines []MachineListJsonMachinesElem `json:"machines"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

type MachineListJsonMachinesElem struct {
	// MachineDisplayName corresponds to the JSON schema field "machine_display_name".
	MachineDisplayName string `json:"machine_display_name"`

	// MachineId corresponds to the JSON schema field "machine_id".
	MachineId string `json:"machine_id"`

	// Sessions corresponds to the JSON schema field "sessions".
	Sessions []MachineListJsonMachinesElemSessionsElem `json:"sessions"`

	// State corresponds to the JSON schema field "state".
	State MachineListJsonMachinesElemState `json:"state"`
}

type MachineListJsonMachinesElemSessionsElem struct {
	// Metadata corresponds to the JSON schema field "metadata".
	Metadata MachineListJsonMachinesElemSessionsElemMetadata `json:"metadata"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id"`

	// State corresponds to the JSON schema field "state".
	State MachineListJsonMachinesElemSessionsElemState `json:"state"`
}

type MachineListJsonMachinesElemSessionsElemMetadata map[string]interface{}

type MachineListJsonMachinesElemSessionsElemState string

const MachineListJsonMachinesElemSessionsElemStateEnded MachineListJsonMachinesElemSessionsElemState = "ended"
const MachineListJsonMachinesElemSessionsElemStateIdle MachineListJsonMachinesElemSessionsElemState = "idle"
const MachineListJsonMachinesElemSessionsElemStatePaused MachineListJsonMachinesElemSessionsElemState = "paused"
const MachineListJsonMachinesElemSessionsElemStateRunning MachineListJsonMachinesElemSessionsElemState = "running"
const MachineListJsonMachinesElemSessionsElemStateUnresponsive MachineListJsonMachinesElemSessionsElemState = "unresponsive"

var enumValues_MachineListJsonMachinesElemSessionsElemState = []interface{}{
	"running",
	"idle",
	"paused",
	"unresponsive",
	"ended",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MachineListJsonMachinesElemSessionsElemState) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MachineListJsonMachinesElemSessionsElemState {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MachineListJsonMachinesElemSessionsElemState, v)
	}
	*j = MachineListJsonMachinesElemSessionsElemState(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MachineListJsonMachinesElemSessionsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["metadata"]; raw != nil && !ok {
		return fmt.Errorf("field metadata in MachineListJsonMachinesElemSessionsElem: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in MachineListJsonMachinesElemSessionsElem: required")
	}
	if _, ok := raw["state"]; raw != nil && !ok {
		return fmt.Errorf("field state in MachineListJsonMachinesElemSessionsElem: required")
	}
	type Plain MachineListJsonMachinesElemSessionsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = MachineListJsonMachinesElemSessionsElem(plain)
	return nil
}

type MachineListJsonMachinesElemState string

const MachineListJsonMachinesElemStateOffline MachineListJsonMachinesElemState = "offline"
const MachineListJsonMachinesElemStateOnline MachineListJsonMachinesElemState = "online"
const MachineListJsonMachinesElemStateSuspended MachineListJsonMachinesElemState = "suspended"

var enumValues_MachineListJsonMachinesElemState = []interface{}{
	"online",
	"suspended",
	"offline",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MachineListJsonMachinesElemState) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MachineListJsonMachinesElemState {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MachineListJsonMachinesElemState, v)
	}
	*j = MachineListJsonMachinesElemState(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MachineListJsonMachinesElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["machine_display_name"]; raw != nil && !ok {
		return fmt.Errorf("field machine_display_name in MachineListJsonMachinesElem: required")
	}
	if _, ok := raw["machine_id"]; raw != nil && !ok {
		return fmt.Errorf("field machine_id in MachineListJsonMachinesElem: required")
	}
	if _, ok := raw["sessions"]; raw != nil && !ok {
		return fmt.Errorf("field sessions in MachineListJsonMachinesElem: required")
	}
	if _, ok := raw["state"]; raw != nil && !ok {
		return fmt.Errorf("field state in MachineListJsonMachinesElem: required")
	}
	type Plain MachineListJsonMachinesElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = MachineListJsonMachinesElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MachineListJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["machines"]; raw != nil && !ok {
		return fmt.Errorf("field machines in MachineListJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in MachineListJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in MachineListJson: required")
	}
	type Plain MachineListJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = MachineListJson(plain)
	return nil
}
