// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/coordinator-app/replay_unavailable.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package coordinator_app

import "encoding/json"
import "fmt"

// Coordinator -> App. Sent in response to attach when the requested last_seq is
// older than the ring's earliest entry. See SPEC.md §§ 10.3, 18.4.
type ReplayUnavailableJson struct {
	// CurrentSeq corresponds to the JSON schema field "current_seq".
	CurrentSeq int `json:"current_seq"`

	// EarliestAvailableSeq corresponds to the JSON schema field
	// "earliest_available_seq".
	EarliestAvailableSeq int `json:"earliest_available_seq"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ReplayUnavailableJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["current_seq"]; raw != nil && !ok {
		return fmt.Errorf("field current_seq in ReplayUnavailableJson: required")
	}
	if _, ok := raw["earliest_available_seq"]; raw != nil && !ok {
		return fmt.Errorf("field earliest_available_seq in ReplayUnavailableJson: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in ReplayUnavailableJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in ReplayUnavailableJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in ReplayUnavailableJson: required")
	}
	type Plain ReplayUnavailableJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.CurrentSeq {
		return fmt.Errorf("field %s: must be >= %v", "current_seq", 0)
	}
	if 0 > plain.EarliestAvailableSeq {
		return fmt.Errorf("field %s: must be >= %v", "earliest_available_seq", 0)
	}
	*j = ReplayUnavailableJson(plain)
	return nil
}
