// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/coordinator-app/session_started.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package coordinator_app

import "encoding/json"
import "fmt"

// Coordinator -> App. Mirror of the daemon's session_started, broadcast to
// subscribed clients. See SPEC.md § 10.3.
type SessionStartedJson struct {
	// MachineId corresponds to the JSON schema field "machine_id".
	MachineId string `json:"machine_id"`

	// Metadata corresponds to the JSON schema field "metadata".
	Metadata SessionStartedJsonMetadata `json:"metadata"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

type SessionStartedJsonMetadata map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SessionStartedJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["machine_id"]; raw != nil && !ok {
		return fmt.Errorf("field machine_id in SessionStartedJson: required")
	}
	if _, ok := raw["metadata"]; raw != nil && !ok {
		return fmt.Errorf("field metadata in SessionStartedJson: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in SessionStartedJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SessionStartedJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in SessionStartedJson: required")
	}
	type Plain SessionStartedJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SessionStartedJson(plain)
	return nil
}
