// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/coordinator-app/spawn_response.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package coordinator_app

import "encoding/json"
import "fmt"

// Coordinator -> App. Relayed spawn_response delivered only to the originating
// client. See SPEC.md §§ 10.3, 15.
type SpawnResponseJson struct {
	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty,omitzero"`

	// RequestId corresponds to the JSON schema field "request_id".
	RequestId string `json:"request_id"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId *string `json:"session_id,omitempty,omitzero"`

	// Success corresponds to the JSON schema field "success".
	Success bool `json:"success"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpawnResponseJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["request_id"]; raw != nil && !ok {
		return fmt.Errorf("field request_id in SpawnResponseJson: required")
	}
	if _, ok := raw["success"]; raw != nil && !ok {
		return fmt.Errorf("field success in SpawnResponseJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SpawnResponseJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in SpawnResponseJson: required")
	}
	type Plain SpawnResponseJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SpawnResponseJson(plain)
	return nil
}
