// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/coordinator-app/subscribe_machine_list.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package coordinator_app

import "encoding/json"
import "fmt"

// App -> Coordinator. Subscribe to machine and session updates. See SPEC.md §
// 10.3.
type SubscribeMachineListJson struct {
	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SubscribeMachineListJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SubscribeMachineListJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in SubscribeMachineListJson: required")
	}
	type Plain SubscribeMachineListJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SubscribeMachineListJson(plain)
	return nil
}
