// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/daemon-coordinator/abort_session.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package daemon_coordinator

import "encoding/json"
import "fmt"
import "reflect"

// Coordinator -> Daemon. Terminate a Pi session. See SPEC.md § 10.2.
type AbortSessionJson struct {
	// Mode corresponds to the JSON schema field "mode".
	Mode AbortSessionJsonMode `json:"mode"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

type AbortSessionJsonMode string

const AbortSessionJsonModeKill AbortSessionJsonMode = "kill"

var enumValues_AbortSessionJsonMode = []interface{}{
	"kill",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AbortSessionJsonMode) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AbortSessionJsonMode {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_AbortSessionJsonMode, v)
	}
	*j = AbortSessionJsonMode(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AbortSessionJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["mode"]; raw != nil && !ok {
		return fmt.Errorf("field mode in AbortSessionJson: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in AbortSessionJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in AbortSessionJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in AbortSessionJson: required")
	}
	type Plain AbortSessionJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AbortSessionJson(plain)
	return nil
}
