// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/daemon-coordinator/machine_register.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package daemon_coordinator

import "encoding/json"
import "fmt"
import "reflect"

// Daemon -> Coordinator. First message after WebSocket open. See SPEC.md § 10.2.
type MachineRegisterJson struct {
	// Capabilities corresponds to the JSON schema field "capabilities".
	Capabilities []MachineRegisterJsonCapabilitiesElem `json:"capabilities"`

	// DaemonVersion corresponds to the JSON schema field "daemon_version".
	DaemonVersion string `json:"daemon_version"`

	// MachineDisplayName corresponds to the JSON schema field "machine_display_name".
	MachineDisplayName string `json:"machine_display_name"`

	// MachineId corresponds to the JSON schema field "machine_id".
	MachineId string `json:"machine_id"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

type MachineRegisterJsonCapabilitiesElem string

const MachineRegisterJsonCapabilitiesElemMirror MachineRegisterJsonCapabilitiesElem = "mirror"
const MachineRegisterJsonCapabilitiesElemSpawn MachineRegisterJsonCapabilitiesElem = "spawn"

var enumValues_MachineRegisterJsonCapabilitiesElem = []interface{}{
	"spawn",
	"mirror",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MachineRegisterJsonCapabilitiesElem) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MachineRegisterJsonCapabilitiesElem {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MachineRegisterJsonCapabilitiesElem, v)
	}
	*j = MachineRegisterJsonCapabilitiesElem(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MachineRegisterJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["capabilities"]; raw != nil && !ok {
		return fmt.Errorf("field capabilities in MachineRegisterJson: required")
	}
	if _, ok := raw["daemon_version"]; raw != nil && !ok {
		return fmt.Errorf("field daemon_version in MachineRegisterJson: required")
	}
	if _, ok := raw["machine_display_name"]; raw != nil && !ok {
		return fmt.Errorf("field machine_display_name in MachineRegisterJson: required")
	}
	if _, ok := raw["machine_id"]; raw != nil && !ok {
		return fmt.Errorf("field machine_id in MachineRegisterJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in MachineRegisterJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in MachineRegisterJson: required")
	}
	type Plain MachineRegisterJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = MachineRegisterJson(plain)
	return nil
}
