// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/daemon-coordinator/spawn_response.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package daemon_coordinator

// Daemon -> Coordinator (and relayed Coordinator -> App). Reply to a
// spawn_request. See SPEC.md §§ 10.2, 10.3, 15.
type SpawnResponseJson interface{}
