// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/daemon-coordinator/spawn_request.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package daemon_coordinator

import "encoding/json"
import "fmt"

// Coordinator -> Daemon. Asks the daemon to spawn a new Pi session in tmux. See
// SPEC.md §§ 10.2, 14.3, 15.
type SpawnRequestJson struct {
	// Cwd corresponds to the JSON schema field "cwd".
	Cwd string `json:"cwd"`

	// ProjectOverride corresponds to the JSON schema field "project_override".
	ProjectOverride SpawnRequestJsonProjectOverride `json:"project_override,omitempty,omitzero"`

	// RequestId corresponds to the JSON schema field "request_id".
	RequestId string `json:"request_id"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

type SpawnRequestJsonProjectOverride *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpawnRequestJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["cwd"]; raw != nil && !ok {
		return fmt.Errorf("field cwd in SpawnRequestJson: required")
	}
	if _, ok := raw["request_id"]; raw != nil && !ok {
		return fmt.Errorf("field request_id in SpawnRequestJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SpawnRequestJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in SpawnRequestJson: required")
	}
	type Plain SpawnRequestJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SpawnRequestJson(plain)
	return nil
}
