// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/coordinator-app/attach.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package coordinator_app

import "encoding/json"
import "fmt"

// App -> Coordinator. Attach to a session and request replay starting after
// `last_seq`. See SPEC.md §§ 10.3, 18.4.
type AttachJson struct {
	// 0 means stream all available history then go live.
	LastSeq int `json:"last_seq,omitempty,omitzero"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AttachJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in AttachJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in AttachJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in AttachJson: required")
	}
	type Plain AttachJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["last_seq"]; !ok || v == nil {
		plain.LastSeq = 0
	}
	if 0 > plain.LastSeq {
		return fmt.Errorf("field %s: must be >= %v", "last_seq", 0)
	}
	*j = AttachJson(plain)
	return nil
}
