// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/coordinator-app/machine_state_change.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package coordinator_app

import "encoding/json"
import "fmt"
import "reflect"

// Coordinator -> App. Single-machine state delta. See SPEC.md § 10.3.
type MachineStateChangeJson struct {
	// MachineId corresponds to the JSON schema field "machine_id".
	MachineId string `json:"machine_id"`

	// State corresponds to the JSON schema field "state".
	State MachineStateChangeJsonState `json:"state"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

type MachineStateChangeJsonState string

const MachineStateChangeJsonStateOffline MachineStateChangeJsonState = "offline"
const MachineStateChangeJsonStateOnline MachineStateChangeJsonState = "online"
const MachineStateChangeJsonStateSuspended MachineStateChangeJsonState = "suspended"

var enumValues_MachineStateChangeJsonState = []interface{}{
	"online",
	"suspended",
	"offline",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MachineStateChangeJsonState) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MachineStateChangeJsonState {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MachineStateChangeJsonState, v)
	}
	*j = MachineStateChangeJsonState(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MachineStateChangeJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["machine_id"]; raw != nil && !ok {
		return fmt.Errorf("field machine_id in MachineStateChangeJson: required")
	}
	if _, ok := raw["state"]; raw != nil && !ok {
		return fmt.Errorf("field state in MachineStateChangeJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in MachineStateChangeJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in MachineStateChangeJson: required")
	}
	type Plain MachineStateChangeJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = MachineStateChangeJson(plain)
	return nil
}
