// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/coordinator-app/session_state_change.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package coordinator_app

import "encoding/json"
import "fmt"
import "reflect"

// Coordinator -> App. Forwarded session state transition with machine_id added.
// See SPEC.md § 10.3.
type SessionStateChangeJson struct {
	// From corresponds to the JSON schema field "from".
	From State `json:"from"`

	// MachineId corresponds to the JSON schema field "machine_id".
	MachineId string `json:"machine_id"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id"`

	// To corresponds to the JSON schema field "to".
	To State `json:"to"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SessionStateChangeJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["from"]; raw != nil && !ok {
		return fmt.Errorf("field from in SessionStateChangeJson: required")
	}
	if _, ok := raw["machine_id"]; raw != nil && !ok {
		return fmt.Errorf("field machine_id in SessionStateChangeJson: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in SessionStateChangeJson: required")
	}
	if _, ok := raw["to"]; raw != nil && !ok {
		return fmt.Errorf("field to in SessionStateChangeJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SessionStateChangeJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in SessionStateChangeJson: required")
	}
	type Plain SessionStateChangeJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SessionStateChangeJson(plain)
	return nil
}

type State string

const StateEnded State = "ended"
const StateIdle State = "idle"
const StatePaused State = "paused"
const StateRunning State = "running"
const StateUnresponsive State = "unresponsive"

var enumValues_State = []interface{}{
	"running",
	"idle",
	"paused",
	"unresponsive",
	"ended",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *State) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_State {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_State, v)
	}
	*j = State(v)
	return nil
}
