// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/coordinator-app/session_ended.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package coordinator_app

import "encoding/json"
import "fmt"
import "reflect"

// Coordinator -> App. Forwarded session_ended that includes machine_id. See
// SPEC.md § 10.3.
type SessionEndedJson struct {
	// MachineId corresponds to the JSON schema field "machine_id".
	MachineId string `json:"machine_id"`

	// Reason corresponds to the JSON schema field "reason".
	Reason SessionEndedJsonReason `json:"reason"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

type SessionEndedJsonReason string

const SessionEndedJsonReasonExtensionDisconnect SessionEndedJsonReason = "extension_disconnect"
const SessionEndedJsonReasonKilled SessionEndedJsonReason = "killed"
const SessionEndedJsonReasonProcessExit SessionEndedJsonReason = "process_exit"
const SessionEndedJsonReasonSpawnFailed SessionEndedJsonReason = "spawn_failed"
const SessionEndedJsonReasonTmuxServerLost SessionEndedJsonReason = "tmux_server_lost"

var enumValues_SessionEndedJsonReason = []interface{}{
	"process_exit",
	"extension_disconnect",
	"tmux_server_lost",
	"killed",
	"spawn_failed",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SessionEndedJsonReason) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SessionEndedJsonReason {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SessionEndedJsonReason, v)
	}
	*j = SessionEndedJsonReason(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SessionEndedJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["machine_id"]; raw != nil && !ok {
		return fmt.Errorf("field machine_id in SessionEndedJson: required")
	}
	if _, ok := raw["reason"]; raw != nil && !ok {
		return fmt.Errorf("field reason in SessionEndedJson: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in SessionEndedJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SessionEndedJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in SessionEndedJson: required")
	}
	type Plain SessionEndedJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SessionEndedJson(plain)
	return nil
}
