// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/coordinator-app/spawn_session.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package coordinator_app

import "encoding/json"
import "fmt"

// App -> Coordinator. Asks coordinator to relay a spawn request to the named
// machine. See SPEC.md §§ 10.3, 15.
type SpawnSessionJson struct {
	// Cwd corresponds to the JSON schema field "cwd".
	Cwd string `json:"cwd"`

	// MachineId corresponds to the JSON schema field "machine_id".
	MachineId string `json:"machine_id"`

	// ProjectOverride corresponds to the JSON schema field "project_override".
	ProjectOverride SpawnSessionJsonProjectOverride `json:"project_override,omitempty,omitzero"`

	// RequestId corresponds to the JSON schema field "request_id".
	RequestId string `json:"request_id"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

type SpawnSessionJsonProjectOverride *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpawnSessionJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["cwd"]; raw != nil && !ok {
		return fmt.Errorf("field cwd in SpawnSessionJson: required")
	}
	if _, ok := raw["machine_id"]; raw != nil && !ok {
		return fmt.Errorf("field machine_id in SpawnSessionJson: required")
	}
	if _, ok := raw["request_id"]; raw != nil && !ok {
		return fmt.Errorf("field request_id in SpawnSessionJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SpawnSessionJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in SpawnSessionJson: required")
	}
	type Plain SpawnSessionJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SpawnSessionJson(plain)
	return nil
}
