// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/extension-daemon/event.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package extension_daemon

import "encoding/json"
import "fmt"
import "reflect"

// Extension -> Daemon. Projection of a Pi event onto Pi Remote's protocol. See
// SPEC.md §§ 6.4, 10.1.
type EventJson struct {
	// Kind-specific payload. Free-form for v1; per-kind shapes are documented in
	// SPEC.md § 6.4.
	Data EventJsonData `json:"data"`

	// Kind corresponds to the JSON schema field "kind".
	Kind EventJsonKind `json:"kind"`

	// Unix epoch milliseconds.
	Ts int `json:"ts"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

// Kind-specific payload. Free-form for v1; per-kind shapes are documented in
// SPEC.md § 6.4.
type EventJsonData map[string]interface{}

type EventJsonKind string

const EventJsonKindAgentEnd EventJsonKind = "agent_end"
const EventJsonKindAgentStart EventJsonKind = "agent_start"
const EventJsonKindAttentionDialog EventJsonKind = "attention_dialog"
const EventJsonKindCompactionEnd EventJsonKind = "compaction_end"
const EventJsonKindCompactionStart EventJsonKind = "compaction_start"
const EventJsonKindExtensionError EventJsonKind = "extension_error"
const EventJsonKindModelSelect EventJsonKind = "model_select"
const EventJsonKindQueueUpdate EventJsonKind = "queue_update"
const EventJsonKindToolFailure EventJsonKind = "tool_failure"

var enumValues_EventJsonKind = []interface{}{
	"agent_start",
	"agent_end",
	"attention_dialog",
	"tool_failure",
	"queue_update",
	"model_select",
	"compaction_start",
	"compaction_end",
	"extension_error",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EventJsonKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EventJsonKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EventJsonKind, v)
	}
	*j = EventJsonKind(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EventJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in EventJson: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in EventJson: required")
	}
	if _, ok := raw["ts"]; raw != nil && !ok {
		return fmt.Errorf("field ts in EventJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in EventJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in EventJson: required")
	}
	type Plain EventJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.Ts {
		return fmt.Errorf("field %s: must be >= %v", "ts", 0)
	}
	*j = EventJson(plain)
	return nil
}
