// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/extension-daemon/register.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package extension_daemon

import "encoding/json"
import "fmt"

// Extension -> Daemon. First message after the extension connects to the Unix
// socket. See SPEC.md § 10.1.
type RegisterJson struct {
	// Cwd corresponds to the JSON schema field "cwd".
	Cwd string `json:"cwd"`

	// Hostname corresponds to the JSON schema field "hostname".
	Hostname string `json:"hostname"`

	// Model corresponds to the JSON schema field "model".
	Model string `json:"model"`

	// Pid corresponds to the JSON schema field "pid".
	Pid int `json:"pid"`

	// ProjectDisplayName corresponds to the JSON schema field "project_display_name".
	ProjectDisplayName RegisterJsonProjectDisplayName `json:"project_display_name,omitempty,omitzero"`

	// ProjectName corresponds to the JSON schema field "project_name".
	ProjectName string `json:"project_name"`

	// Pi session UUID (UUIDv7).
	SessionId string `json:"session_id"`

	// Hex-encoded 32-character spawn token (D6) when the daemon spawned this Pi
	// process; null/absent when user-spawned.
	SpawnToken RegisterJsonSpawnToken `json:"spawn_token,omitempty,omitzero"`

	// Unix epoch milliseconds at which the Pi process started.
	StartedAt int `json:"started_at"`

	// tmux pane target string in `session:window.pane` form.
	TmuxTarget string `json:"tmux_target"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

type RegisterJsonProjectDisplayName *string

// Hex-encoded 32-character spawn token (D6) when the daemon spawned this Pi
// process; null/absent when user-spawned.
type RegisterJsonSpawnToken *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *RegisterJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["cwd"]; raw != nil && !ok {
		return fmt.Errorf("field cwd in RegisterJson: required")
	}
	if _, ok := raw["hostname"]; raw != nil && !ok {
		return fmt.Errorf("field hostname in RegisterJson: required")
	}
	if _, ok := raw["model"]; raw != nil && !ok {
		return fmt.Errorf("field model in RegisterJson: required")
	}
	if _, ok := raw["pid"]; raw != nil && !ok {
		return fmt.Errorf("field pid in RegisterJson: required")
	}
	if _, ok := raw["project_name"]; raw != nil && !ok {
		return fmt.Errorf("field project_name in RegisterJson: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in RegisterJson: required")
	}
	if _, ok := raw["started_at"]; raw != nil && !ok {
		return fmt.Errorf("field started_at in RegisterJson: required")
	}
	if _, ok := raw["tmux_target"]; raw != nil && !ok {
		return fmt.Errorf("field tmux_target in RegisterJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in RegisterJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in RegisterJson: required")
	}
	type Plain RegisterJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain.Pid {
		return fmt.Errorf("field %s: must be >= %v", "pid", 1)
	}
	if 0 > plain.StartedAt {
		return fmt.Errorf("field %s: must be >= %v", "started_at", 0)
	}
	*j = RegisterJson(plain)
	return nil
}
