// SPDX-License-Identifier: MIT
// GENERATED — DO NOT EDIT. Source: pi-remote-spec/protocol/extension-daemon/register_ack.json

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package extension_daemon

import "encoding/json"
import "fmt"

// Daemon -> Extension. Reply to a `register`. See SPEC.md § 10.1.
type RegisterAckJson struct {
	// Accepted corresponds to the JSON schema field "accepted".
	Accepted bool `json:"accepted"`

	// Present and informative when `accepted` is false.
	Reason *string `json:"reason,omitempty,omitzero"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId string `json:"session_id"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`

	// V corresponds to the JSON schema field "v".
	V interface{} `json:"v"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RegisterAckJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["accepted"]; raw != nil && !ok {
		return fmt.Errorf("field accepted in RegisterAckJson: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in RegisterAckJson: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in RegisterAckJson: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in RegisterAckJson: required")
	}
	type Plain RegisterAckJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = RegisterAckJson(plain)
	return nil
}
